#! /bin/bash


felix_pid(){
	echo `ps aux | grep felix.jar | grep -v grep | awk '{ print $2 }'`
}

start(){
	pid=$(felix_pid)
	if [ -n "$pid" ]
	then
		echo "FELIX is already running (pid: $pid)"
	else

        echo "Starting felix.."

        sudo -u explinuser java -Dgosh.args=--nointeractive -jar bin/felix.jar >log.log 2>log.log &
	fi
}

stop(){
        echo "Stopping felix.."
        sudo -u explinuser kill $(felix_pid)
}

restart(){
        stop
# give stuff some time to stop before we restart
        sleep 60
        start
}




case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  *)
        echo "Usage: explin {start|stop|restart}"
        exit 1
esac

exit 0
