#! /bin/bash
# chkconfig:   2345 80 20
# description: Start and Stop Explin RESTfull API

EXPLIN_USER=explinuser
FELIX_HOME=/mnt/apps/explin/felix-framework-4.6.1/

felix_pid(){
	echo `ps aux | grep felix.jar | grep -v grep | awk '{ print $2 }'`
}

start(){
	pid=$(felix_pid)
	if [ -n "$pid" ]
	then
		echo "FELIX is already running (pid: $pid)"
	else

        echo "Starting felix.."

        cd $FELIX_HOME && sudo -u $EXPLIN_USER java -Dgosh.args=--nointeractive -jar bin/felix.jar >log.log 2>log.log &
	fi
}

stop(){
        echo "Stopping felix.."
        sudo -u $EXPLIN_USER kill $(felix_pid)
}

restart(){
        stop
# give stuff some time to stop before we restart
        sleep 60
        start
}
status(){
	pidfelix=$(felix_pid)
	if [ -n "$pidfelix" ]
	then
		echo "felix is running (pid: $pidfelix)"
	else
		echo "felix is down "
	fi
}


case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  status)
	  	status
	  	;;
  *)
        echo "Usage: explin {start|stop|restart|status}"
        exit 1
esac

exit 0
